# Generated by Django 4.2 on 2026-06-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Salida',
            },
        ),
    ]
