# Generated by Django 4.2 on 2026-06-10 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medicos', '0001_initial'),
        ('Pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitasMedicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('atendida', models.BooleanField(default=False)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Medicos.medicos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pacientes.pacientes')),
            ],
            options={
                'verbose_name_plural': 'Citas Medicas',
            },
        ),
    ]
